#!/bin/sh
export GEM_HOME="{{pkg.svc_static_path}}/vendor/bundle/ruby/2.3.0"
export GEM_PATH="$(hab pkg path core/ruby)/lib/ruby/gems/2.3.0:$(hab pkg path core/bundler):$GEM_HOME"
export LD_LIBRARY_PATH="$(hab pkg path core/gcc-libs)/lib"
export RAILS_ENV="development"

cd {{pkg.svc_static_path}}

# exec chpst -u hab bundle config --delete bin 
# exec chpst -u hab ./bin/rails app:update:bin

exec 2>&1
exec chpst -u hab ./bin/rails server